; PlatformIO Project Configuration File
;
; WiFi 4-Kanal Relaiscontroller mit RTC (ESP32 / Arduino)
;
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time

board_build.filesystem = littlefs

lib_deps =
	adafruit/RTClib@^2.1.4
	esp32async/ESPAsyncWebServer@^3.12.0
	esp32async/AsyncTCP@^3.5.0
	bblanchon/ArduinoJson@^7.2.1
	jpb10/SolarCalculator@^2.0.2

build_flags =
	-DCORE_DEBUG_LEVEL=1
